### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by vadi2** [kripken/lua.vm.js#52] opened 2016-04-21 08:20 UTC
Chrome says the following warning:

``Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/``

**Comment by daurnimator** [comment] 2016-04-29 06:13
Duplicate of #25

**Closed by daurnimator** 2016-04-29 06:13 UTC
